# **Predicting Bank Customer Churn using ANN**

# Problem Statment

The bank seeks to develop a predictive model to prevent customer churn. The objective is to accurately predict which customers are at risk of churning in the near future. By identifying potential churners early, the bank can implement targeted retention strategies to mitigate attrition and enhance customer satisfaction.

# Importing the dependinces

In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [4]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X = df.iloc[: , 3:13].values
y = df.iloc[: , -1].values

X.shape,y.shape

((10000, 10), (10000,))

In [6]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

#  Data Preproccesing

In [7]:
Gender_encoder = LabelEncoder()
X[:,2] = Gender_encoder.fit_transform(X[:,2])

In [8]:
print(X)
print(X.shape)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
(10000, 10)


In [9]:
one_hot_encoder = OneHotEncoder(categories='auto', sparse=False)  # sparse=False to get dense array
X_encoded = one_hot_encoder.fit_transform(X[:, [1]])

# Replace column 1 with the one-hot encoded values
X = np.concatenate((X[:, :1], X_encoded, X[:, 2:]), axis=1)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [10]:
print(X)
print(X.shape)

[[619 1.0 0.0 ... 1 1 101348.88]
 [608 0.0 0.0 ... 0 1 112542.58]
 [502 1.0 0.0 ... 1 0 113931.57]
 ...
 [709 1.0 0.0 ... 0 1 42085.58]
 [772 0.0 1.0 ... 1 0 92888.52]
 [792 1.0 0.0 ... 1 0 38190.78]]
(10000, 12)


# Spliting the data for modeling

In [11]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature Scaling


In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train

array([[ 0.35649971,  1.00150113, -0.57946723, ...,  0.64920267,
         0.97481699,  1.36766974],
       [-0.20389777, -0.99850112,  1.72572313, ...,  0.64920267,
         0.97481699,  1.6612541 ],
       [-0.96147213, -0.99850112, -0.57946723, ...,  0.64920267,
        -1.02583358, -0.25280688],
       ...,
       [ 0.86500853,  1.00150113, -0.57946723, ..., -1.54035103,
        -1.02583358, -0.1427649 ],
       [ 0.15932282,  1.00150113, -0.57946723, ...,  0.64920267,
        -1.02583358, -0.05082558],
       [ 0.47065475, -0.99850112,  1.72572313, ...,  0.64920267,
         0.97481699, -0.81456811]])

# Creating the Artificial Neural Network

In [14]:
# intialization the ANN

classifer = Sequential()

# adding the input layer
classifer.add(Dense(6,activation='relu', kernel_initializer='uniform'))


In [15]:
# adding hidden layer
classifer.add(Dense(6,activation='relu',kernel_initializer='uniform'))

In [16]:
# adding the output layer for prediction
classifer.add(Dense(1,activation='sigmoid',kernel_initializer='uniform'))

In [17]:
classifer.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [18]:
# Training the model
classifer.fit(X_train,y_train,batch_size=10,epochs=15)

Epoch 1/15
800/800 [==============================] - 5s 4ms/step - loss: 0.4896 - accuracy: 0.7941
Epoch 2/15
800/800 [==============================] - 2s 3ms/step - loss: 0.4317 - accuracy: 0.7945
Epoch 3/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4249 - accuracy: 0.7966
Epoch 4/15
800/800 [==============================] - 1s 2ms/step - loss: 0.4204 - accuracy: 0.8221
Epoch 5/15
800/800 [==============================] - 1s 2ms/step - loss: 0.4175 - accuracy: 0.8295
Epoch 6/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4158 - accuracy: 0.8300
Epoch 7/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4138 - accuracy: 0.8332
Epoch 8/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4127 - accuracy: 0.8329
Epoch 9/15
800/800 [==============================] - 2s 2ms/step - loss: 0.4116 - accuracy: 0.8346
Epoch 10/15
800/800 [==============================] - 2s 3ms/step - loss: 0.4108 - accuracy: 0.8341

In [19]:
# Testing the model
classifer.predict(X_test)

63/63 [==============================] - 0s 2ms/step


array([[0.13934359],
       [0.08199137],
       [0.40884194],
       ...,
       [0.47124115],
       [0.03135199],
       [0.2175855 ]], dtype=float32)

In [21]:
# Evaluating the model
test_loss , test_acc = classifer.evaluate(X_test,y_test)
print(f'loss cost value {test_loss}')
print(f'accuracy value for testing {test_acc}')

63/63 [==============================] - 0s 3ms/step - loss: 0.3923 - accuracy: 0.8415
loss cost value 0.3923177421092987
accuracy value for testing 0.8414999842643738
